version: '3.8'

services:
  app:
    container_name: restaurant_service
    build: ./
    depends_on:
      - db
    command: "bash -c 'while !</dev/tcp/${DB_CONTAINER}/${DB_PORT2}; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'"
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: "no"
    env_file:
      - .env

  db:
    container_name: ${DB_CONTAINER}
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT2}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env


  migrate:
    container_name: restaurant_migration
    build: ./
    depends_on:
      - app
    command: "bash -c 'alembic revision --autogenerate; alembic upgrade head'"
    volumes:
      - ./app:/src/app
    env_file:
      - .env

volumes:
  pgdata:
